apiVersion: v1
kind: ConfigMap
metadata:
  name: easyshop-config
  namespace: easyshop
data:
  # MongoDB URI pointing to the service inside the cluster
  MONGODB_URI: "mongodb://mongodb-0.mongodb.easyshop.svc.cluster.local:27017"

  # Redis service URL (update if your redis service name differs)
  REDIS_URI: "redis://easyshop-redis.easyshop.svc.cluster.local:6379"

  # Environment configuration
  NODE_ENV: "production"
  NEXTAUTH_URL: "http://aeee48da051b24093b7b5cfb7a4952e3-1402525880.eu-north-1.elb.amazonaws.com/"
  NEXT_PUBLIC_API_URL: "http://aeee48da051b24093b7b5cfb7a4952e3-1402525880.eu-north-1.elb.amazonaws.com/api"
