apiVersion: v1
kind: Secret
metadata:
  name: easyshop-secrets
  namespace: easyshop
type: Opaque
stringData:
  NEXTAUTH_SECRET: "1/WYvzXsiH/wOJKVcTtMC4qY019ewKJkX01zJhP7APk="
  JWT_SECRET: "481060dac13a454c0a0103e76b54b45a050052e68207b7f1a944d32a7b49618a"
