apiVersion: v1
kind: ConfigMap
metadata:
  name: easyshop-config
  namespace: easyshop
data:
  # MongoDB URI pointing to the service inside the cluster
  MONGODB_URI: "mongodb://mongodb-service.easyshop.svc.cluster.local:27017/easyshop"

  # Redis service URL (update if your redis service name differs)
  REDIS_URI: "redis://easyshop-redis.easyshop.svc.cluster.local:6379"

  # Environment configuration
  NODE_ENV: "production"
  NEXTAUTH_URL: "http://afe4454f8f14d4b4b837816ed0c7d804-1491358452.eu-north-1.elb.amazonaws.com/"
  NEXT_PUBLIC_API_URL: "http://afe4454f8f14d4b4b837816ed0c7d804-1491358452.eu-north-1.elb.amazonaws.com/api"
