apiVersion: batch/v1
kind: Job
metadata:
  name: db-migrate
  namespace: easyshop
spec:
  backoffLimit: 4
  template:
    spec:
      containers:
        - name: dbmigrate
          image: krushnajhn/easy-shop-migration:tagname
          imagePullPolicy: IfNotPresent
          env:
            - name: MONGODB_URI
              value: "mongodb://mongodb-service.easyshop.svc.cluster.local:27017/easyshop"
      restartPolicy: Never

