apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: mongo-pvc
  namespace: easyshop   # Replace with your namespace or remove if using default
spec:   # Must match PV's storageClassName
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: 1Gi
