apiVersion: v1
kind: Secret
metadata:
  name: easyshop-secrets
  namespace: easyshop
type: Opaque
stringData:
  NEXTAUTH_SECRET: "nXoVNFpapTXGAR+Pk/v6mPDB4l50PfaV0giwqGNF2/s="
  JWT_SECRET: "d41381973810444cc60014dc25d9cb7e927c272c90b50ef1fd9483a3320905ed"
