apiVersion: v1
kind: Secret
metadata:
  name: easyshop-secrets
  namespace: easyshop
type: Opaque
stringData:
  NEXTAUTH_SECRET: "YS4bYrzPduA2/saNW0OmLVvcXNJyGKcP/rMA+5BibHg="
  JWT_SECRET: "38fbc4aeeb129792778fc0c26a3dbb17d9a35e6cd1dbe09adbcdbb9fbae4ffbc"
