apiVersion: v1
kind: ConfigMap
metadata:
  name: ts-config
  namespace: easyshop
data:
  tsconfig.json: |
    {
      "compilerOptions": {
        "target": "es2016",
        "module": "commonjs",
        "esModuleInterop": true,
        "forceConsistentCasingInFileNames": true,
        "strict": true,
        "skipLibCheck": true,
        "outDir": "./dist"
      }
    }
---
apiVersion: batch/v1
kind: Job
metadata:
  name: db-migration-job-v2
  namespace: easyshop
spec:
  backoffLimit: 2
  template:
    spec:
      volumes:
      - name: ts-config-volume
        configMap:
          name: ts-config
      containers:
      - name: migration
        image: iemafzal/easyshop-migration:9
        envFrom:
          - configMapRef:
              name: easyshop-config
          - secretRef:
              name: easyshop-secrets
        env:
        - name: MONGODB_URI
          value: "mongodb://mongodb-0.mongodb-service.easyshop.svc.cluster.local:27017/easyshop"
        - name: NODE_ENV
          value: "development"
        volumeMounts:
        - name: ts-config-volume
          mountPath: /app/scripts/tsconfig.json
          subPath: tsconfig.json
      restartPolicy: Never 
